SELECT 
    ID,
    CASE 
        WHEN PER_GROUP = 1 THEN 'CRITICAL'
        WHEN PER_GROUP = 2 THEN 'HIGH'
        WHEN PER_GROUP = 3 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM (
    SELECT 
        ID,
        NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS PER_GROUP
    FROM ECOLI_DATA
) SUB
ORDER BY ID ASC;