SELECT
    B.WRITER_ID AS USER_ID,
    U.NICKNAME,
    SUM(CASE
            WHEN STATUS = 'DONE' THEN PRICE
            ELSE 0
        END) AS TOTAL_SALES
FROM USED_GOODS_BOARD B
INNER JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
GROUP BY B.WRITER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES;