SELECT 
    C.ITEM_ID, 
    C.ITEM_NAME, 
    C.RARITY
FROM ITEM_INFO C
INNER JOIN ITEM_TREE T ON C.ITEM_ID = T.ITEM_ID
INNER JOIN ITEM_INFO P ON T.PARENT_ITEM_ID = P.ITEM_ID
WHERE P.RARITY = 'RARE'
ORDER BY C.ITEM_ID DESC;